### ISSUE TITLE
grep ignores case when looking for an exact match of the peer string

### ISSUE THREAD

**Issue by 86x** [amitn322/wireguard#6]
``
user=`grep -irl ${peer} /etc/wireguard/clients/ | awk -F'/' {'print $5'}`
``
in wireguard-logging.sh ignores case when searching for an **exact** match of the peer string.
I admit it is very unlikely that the same peer string will be generated by wireguard for a different user in a different case, but the `i` option should not be used.

From man grep:
```
-i, --ignore-case
              Ignore  case  distinctions  in  patterns and input data, so that
              characters that differ only in case match each other.
```

**Comment by amitn322** [comment]
I agree, I will look into it and merge the pull request.
