### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by 86x** [amitn322/wireguard#8]
This code is really, really useful to me and I might want to make some additional changes which I think don't fit quite well into this repository.
If you could be so kind to add a LICENSE file (like the [BSD 3-Clause license](https://opensource.org/licenses/BSD-3-Clause)) then maybe one day other people, including me, could legally build upon your work (while still mentioning your work) and publish more open source work.

I would be very happy to see that but would also understand if you don't want other people to use your work.

**Comment by amitn322** [comment]
Hi @86x  I am opening to adding the license. I will look into it and update as soon as time permits.

Thank You !

**Comment by amitn322** [comment]
Added the license file.
